# Generated by Django 5.0.4 on 2024-06-11 14:37

import datetime
import django.db.models.deletion
import utils.get_uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_alter_userfiles_file_name_alter_userfiles_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSession',
            fields=[
                ('session_id', models.UUIDField(default=utils.get_uuid.get_unique_id, primary_key=True, serialize=False)),
                ('session_otp', models.IntegerField(default=utils.get_uuid.generate_otp)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('opened', models.BooleanField(default=False)),
                ('timeout', models.TimeField(default=datetime.timedelta(seconds=600))),
                ('files', models.ManyToManyField(related_name='files_included', to='api_v1.userfiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'session_otp')},
            },
        ),
    ]
